# Basic Information
url: https://allenjin123.github.io
baseurl: ""
title: Haoran Jin
position: Ph.D. Candidate in Computer Engineering
affiliation: University of Michigan
affiliation_link: https://www.umich.edu/
email: allenjin (at) umich.edu

# Search Engine Optimization (SEO)
keywords: Haoran Jin, computer architecture, electronic design automation, EDA, hardware-software codesign, chiplet, neural network accelerator, ASIP, stochastic computing, University of Michigan
description: Haoran Jin is a Ph.D. candidate in Computer Engineering at the University of Michigan working on computer architecture and electronic design automation.
canonical: https://allenjin123.github.io/

# Links
# If you don't need one of them, comment out the corresponding line.
google_scholar: https://scholar.google.com/citations?user=fEFlixsAAAAJ
cv_link: /files/HaoranJin_CV.pdf
github_link: https://github.com/Allenjin123
linkedin: https://www.linkedin.com/in/haoran-jin-2a5578309/
# twitter: https://twitter.com/your-handle

# Images (profile picture and favicons)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote ("Powered by Jekyll and Minimal Light theme.")
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font: "Serif" or "Sans Serif"
font: "Serif"

# Google Analytics ID (add your own if desired)
# google_analytics: UA-XXXXXXXX-X

# Plugins
plugins:
  - jekyll-sitemap

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
